function K = quad_kern(x,r,a,b,c)
K = ( 0.5*(x-r).^2 - ((x-a)*(x-c)*(b-r).^2)/(2*(b-a)*(b-c)) - ((x-a)*(x-b)*(c-r).^2)/(2*(c-a)*(c-b)) ).*(a < r & r < x)...
    + ( - ((x-a)*(x-c)*(b-r).^2)/(2*(b-a)*(b-c)) - ((x-a)*(x-b)*(c-r).^2)/(2*(c-a)*(c-b)) ).*(x < r & r < b)...
    + ( - ((x-a)*(x-b)*(c-r).^2)/(2*(c-a)*(c-b)) ).*(b < r & r < c);
end 